name: taxdata-dev
channels:
- conda-forge
dependencies:
- python>=3.6.5
- numpy>=1.12.1
- pandas>=0.20.3
- scipy>=0.18.1
- bokeh>=0.12.3
- statsmodels
- pytest
- pulp
- tqdm
- requests
- lxml
- xlrd
- pulp
- paramtools
- pypandoc
- selenium
- python-chromedriver-binary
- tabulate
- pre-commit
- taxcalc>=3.0.0
- pip
- pip:
  - requests-html
  - black
  - jupyter-book>=0.9.1
